spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
      file-size-threshold: -1
      enabled: true
  datasource:
    username: ${{ MySQL.MYSQLUSER }}
    url: jdbc:mysql://${{ MySQL.MYSQLHOST }}:${{ MySQL.MYSQLPORT }}/${{ MYSQL.MYSQL_DATABASE }} #jdbc:mysql://monorail.proxy.rlwy.net:55053/railway
    password: ${{ MySQL.MYSQLPASSWORD }}
  application:
    name: ciudadania

logging.level:
  org.hibernate.SQL: INFO
  org.hibernate.type.descriptor.sql: INFO

server:
  port: '8081'


