spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
      file-size-threshold: -1
      enabled: true
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME} #jdbc:mysql://monorail.proxy.rlwy.net:55053/railway
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  application:
    name: ciudadania

logging.level:
  org.hibernate.SQL: INFO
  org.hibernate.type.descriptor.sql: INFO

#server:
  #port: '8081'